name: Build Raspberry Pi Image

on:
  push:
    branches: [main, master]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux
            extra-sandbox-paths = /usr/bin/qemu-aarch64 /usr/bin/qemu-aarch64-static

      - name: Build SD card image
        run: |
          nix build --extra-experimental-features nix-command --extra-experimental-features flakes .#packages.aarch64-linux.sdcard

      - name: Get image info
        run: |
          ls -la result/sd-image/
          echo "Image built successfully: $(ls result/sd-image/*.img)"
          echo "Image size: $(du -h result/sd-image/*.img)"

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-image
          path: result/sd-image/*.img
          retention-days: 7
